version: "3.9"

services:
  eureka:
    build: ./tic-toe-eureka-server
    ports:
      - "8761:8761"

  engine:
    build: ./tic-toe-engine-service
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=engine
      - session.base-url=http://session:8081
      - ui.base-url=http://ui:80
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka
      - session
      - zipkin

  session:
    build: ./tic-toe-session-service
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=session
      - engine.base-url=http://engine:8080
      - ui.base-url=http://ui:80
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka
      - zipkin

  gateway:
    build: ./tic-toe-api-gateway
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka
      - engine
      - session
      - zipkin

  ui:
    build: ./tic-toe-ui-service
    ports:
      - "4200:80"
    depends_on:
      - engine
      - session

  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"
